name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: rejail/AppleAuthFix
          ref: main
        
      - name: Install theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Build
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
